### ISSUE TITLE
ACT not parsing in instances

### ISSUE THREAD

**Issue by Tway1** [marzent/Bunny-HUD#1]
Continuation of the issue I posted on the main [FF14-MAC_ModSupport](https://github.com/seathasky/FF14-MAC_ModSupport/issues/27)

I've tested Kagerou, MopiMopi and Ember on Safari, Chrome and Firefox browsers and it looks like the issue only happens on Safari. I'm not sure if this means this has ruled out OverlayPlugin as the issue.

Screenshot of the safari console errors on the Kagerou tab
<img width="937" alt="Screenshot 2021-11-25 at 13 56 56" src="https://user-images.githubusercontent.com/94920376/143455007-71f03fd5-f965-4e88-b5de-8c4e78b89f8b.png">

**Comment by Tway1** [comment]
Confirmed by ngld on discord to be a Safari issue:

ngld — Today at 14:09
TL;DR: It's a bug in WebKit's WebSocket implementation. Apparently it's a regression in 15.1 so previous versions should work fine. It's possible that a modified WebSocket server can work around the issue but I'm not sure it's worth the effort.
[14:11]
My general advice would be to stick to Chromium-based renderers/browsers for overlays because they're rarely tested outside Chromium (i.e. Cactbot used to have bugs in Firefox and other browsers because it was always tested in Chromium).

**Comment by marzent** [comment]
Will see if I can work around that (now that its broken for me too on Monterey) but it might take some time

**Comment by seathasky** [comment]
I will also do some testing tomorrow, holiday here today but Friday I have all day to see if we can get it working on Monterey.

**Comment by Tway1** [comment]
Thanks for your help!
