### ISSUE TITLE
BunnyHUD broken with Monterey

### ISSUE THREAD

**Issue by marzent** [marzent/Bunny-HUD#2]
Until https://bugs.webkit.org/show_bug.cgi?id=228296 is fixed there will be issues with using BunnyHUD on Monterey

**Comment by RussellAnas** [comment]
@marzent do we have any workaround till this gets fixed?

**Comment by marzent** [comment]
There is really nothing else you can do atm except for using Chrome of Firefox to display your Overlay on a second Monitor, although I am trying to get cef integrated into BunnyHUD, so that should fix that.

Unfortunately cef is a very finicky piece of software so it might take me a few days (tonight at the earliest if I have the time and everything goes smoothly)

**Comment by marzent** [comment]
solved with 855dbefd4e619202d959e16a3422d45417612a20
