### ISSUE TITLE
Missing overlays.json file

### ISSUE THREAD

**Issue by albeva** [marzent/Bunny-HUD#6]
I was trying to build the app, but it seems to be missing `overlays.json` from the git repo. Could you add that or point out where you originally got it from? Thanks!

**Comment by marzent** [comment]
This repository contains submodules, so you will have to use `git clone --recurse-submodules https://github.com/marzent/Bunny-HUD` 

If you have already cloned and don't want to delete your local repository you can also do a `git submodule init && git submodule update`
